name: Release to Pages
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Starting build"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependences
        run: |
          apt update
          apt install nodejs
          ${{ github.workspace }}build.sh