name: Release to Pages
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Starting build"
      - uses: actions/checkout@v2
			- uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependences
        run: |
          npm install -g svgo svgexport
          ${{ github.workspace }}build.sh