name: Release to Pages
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Starting build"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependences
        run: |
          npm install -g svgo svgexport
      - name: Build
        run: |
          cd ${{ github.workspace }}
          ./build.sh
      - name: Publish to pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: build
